### ISSUE TITLE
[Umbrella] Basic framework

### ISSUE THREAD

**Issue by ddysher** [caicloud/nirvana#2]
Umbrella issue for tracking basic framework tasks, scope:
- [x] Research on existing solutions, pick one or create one
- [x] Proposal on basic framework implementation
- [x] Implementation: Routing, Multiplexing, Middleware, API error package, etc
- [x] Documentation
- [x] Testing

@kdada

**Comment by ddysher** [comment]
@kdada  Updates after 4th meeting (11/17/2017):
- Hopefully we'll make an agreement on basic framework, second round of review is scheduled on 11/24/2017

**Comment by ddysher** [comment]
Updates after 5th meeting:
- merge framework implementation next week; file separate issue if necessary

**Comment by kdada** [comment]
## Architecture Overview
`log` and `errors` are basic for other packages. So I don't explain it in the diagram. 
![image](https://user-images.githubusercontent.com/13895988/34514829-d9a9b43c-f034-11e7-9dee-5c7940755fab.png)

`nirvana` is the root package in the framework. It implements a configurable server structure.
All plugins implement config interface:
```go

// ConfigInstaller is used to install config to service builder.
type ConfigInstaller interface {
	// Name is the external config name.
	Name() string
	// Install installs stuffs before server starting.
	Install(builder service.Builder, config *Config) error
	// Uninstall uninstalls stuffs after server terminating.
	Uninstall(builder service.Builder, config *Config) error
}
```
The startup flow:
![image](https://user-images.githubusercontent.com/13895988/34515618-8cbc6df0-f038-11e7-90b5-71dd770815a2.png)
Definition modifier is special. It only works in service builder and is used to modify definitions. That means if you install some API definitions into nirvana server, you have a chance to modify all definitions globally. The most important usage of modifier is to inject `context.Context` into `Definition.Parameters` as first parameter.

The shutdown flow:
![image](https://user-images.githubusercontent.com/13895988/34515419-a2dc02d6-f037-11e7-95ec-566efcc193f7.png)
All plugins are independent. So plugins are installed and uninstalled without order.

**Comment by kdada** [comment]
# User Guide

Nirvana is an API framework for creating RESTful APIs. This document shows you how to create API services with Nirvana.

## API Descriptor
In Nirvana, All APIs are described by `definition.Descriptor`. Before explaining, An example would let you have a straightforward sense.
```go
// API descriptor.
var echo = definition.Descriptor{
	Path:        "/echo",
	Description: "Echo API",
	Definitions: []definition.Definition{
		{
			Method: definition.Get,
			Function: Echo,
			Consumes: []string{definition.MIMEAll},
			Produces: []string{definition.MIMEText},
			Parameters: []definition.Parameter{
				{
					Source: definition.Query,
					Name: "msg",
					Description: "Corresponding to the second parameter",
					
				},
			},
			Results: []definition.Result{
				{
					Destination: definition.Data,
					Description: "Corresponding to the first result",
				},
				{
					Destination: definition.Error,
					Description: "Corresponding to the second result",
				},
			},
		},
	},
} 

// API function.
func Echo(ctx context.Context, msg string) (string, error) {
	return msg, nil
}
```
It's an echo API descriptor. It may be a bit complex at your first sight, but it should be extremely obvious after you understanding the structure.

First, look at the API function `Echo`. It receives two parameters and returns two results. As the default config, `context.Context` always is the first parameter in API function. Apart form the first parameter, the usage of other parts is normal. As you see, it's an `Echo` function.

As the name of `Descriptor`, it describes what an API is. The API only receives requests like:
```
HTTP Path: /echo[?msg=]
HTTP Method: Get
HTTP Headers:
    Content-Type: Any Type
    Accept: text/plain or */*
```
When a request is coming, Nirvana would parse it and generate function parameters for API function by `Definition.Parameters`. Parameters are converted to the type defined in API function from request. After the execution of API function, Nirvana collects the results and writes to request. `Definition.Produces` decides the format of the result.

## Nirvana Server

After defining API descriptors, the remaining work is creating an server to serve requests:
```go
func main() {
	config := nirvana.NewDefaultConfig("", 8080)
	config.Configure(nirvana.Descriptor(echo))
	log.Infof("Listening on %s:%d", config.IP, config.Port)
	if err := nirvana.NewServer(config).Serve(); err != nil {
		log.Fatal(err)
	}
}
```
Nirvana server has a plugin machanism. All plugins are registered into config. Then server will install them when the server is starting. 
`nirvana.Descriptor()` is a plugin method for installing API descriptors into config. After server starting, you could test echo API by `http://localhost:8080/echo?msg=test`.

## Project layout
```

```

**Comment by ddysher** [comment]
Done 🚀 

I'll create a doc to archive the design part of the issue.
