### ISSUE TITLE
[Umbrella] API validation

### ISSUE THREAD

**Issue by ddysher** [caicloud/nirvana#3]
Umbrella issue for tracking API validation tasks, scopes:
- [x] Research on requirements, e.g. what kind of validation do we need
- [x] Research on existing solutions
- [x] Proposal or demonstration on how validation should work in nirvana
- [x] Integration with basic framework
- [x] Testing

@walktall

**Comment by ddysher** [comment]
@walktall Action Items after 4th meeting:
- LGTM on basic framework implementation (11/24/2017)
- Draft proposal on validation implementation (11/24/2017)

**Comment by walktall** [comment]
How to implement sample:

```
// Package validator usage:

// type Application struct {
// 	Name      string `json:"name" validate:"required,printascii"`
// 	Namespace string `json:"namespace"`
// }

// Definitions: []definition.Definition{
// 	{
// 		Method:   definition.Create,
// 		Function: Handle,
// 		Parameters: []definition.Parameter{
// 			{
// 				Source:    definition.Query,
// 				Name:      "target1",
// 				Operators: []definition.Operator{validator.Var("gt=0,lt=10")},
// 			},
// 			{
// 				Source: definition.Body,
// 				Name:   "app",
// 				// Should we call this automatically?
// 				Operators: []definition.Operator{validator.Struct()},
// 			},
// 		},
// 	},
// },

package validator

import (
	"context"

	"gopkg.in/go-playground/validator.v9"
)

var std = validator.New()

func Var(tag string) func(ctx context.Context, object interface{}) (interface{}, error) {
	return func(ctx context.Context, object interface{}) (interface{}, error) {
		// TODO: error format
		return object, std.VarCtx(ctx, object, tag)
	}
}

func VarWithValue(other interface{}, tag string) func(ctx context.Context, object interface{}) (interface{}, error) {
	return func(ctx context.Context, object interface{}) (interface{}, error) {
		err := std.VarWithValueCtx(ctx, object, other, tag)
		return object, err
	}
}

func Struct() func(ctx context.Context, object interface{}) (interface{}, error) {
	return func(ctx context.Context, object interface{}) (interface{}, error) {
		return object, std.StructCtx(ctx, object)
	}
}

```

**Comment by ddysher** [comment]
Action Items after 5th meeting:
- Integration with basic framework, 12/01/2017

**Comment by ddysher** [comment]
Done 🚀
