### ISSUE TITLE
[Umbrella] Configuration management

### ISSUE THREAD

**Issue by ddysher** [caicloud/nirvana#4]
Umbrella issue for tracking configuration management tasks, scopes:
- [x] Research on cobra and viper
- [x] Research on how oss create wrapper around cobra (kubernetes, docker, etc)
- [x] Proposal on server start up options and configuration management
- [x] Standalone implementation (if necessary and possible) (initial PR @zoumo 11/14)
- [x] Integration with basic framework
- [x] Testing

@zoumo

**Comment by ddysher** [comment]
@zoumo Action Items after 4th meeting:
- Agree on configuration mgmt on 11/24/2017
- Few more changes to existing implementation, e.g.
  - package need rename
  - avoid new concept (e.g. viper)
  - example on configuration file usage
  - need more tests
  - etc

**Comment by ddysher** [comment]
Action Items after 5th meeting:
- Integration of `viper` and `nirvana`, 12/01/2017
- Start looking at log package

**Comment by ddysher** [comment]
Done, but this is superseded by https://github.com/caicloud/nirvana/issues/139 🤣
