### ISSUE TITLE
[Umbrella] OpenAPI generation

### ISSUE THREAD

**Issue by ddysher** [caicloud/nirvana#5]
Umbrella issue for OpenAPI generation tasks, scopes:
- [x] Research on kubernetes codegen
- [x] Introduction on codegen, background and how it works, etc (11/07 @liubog2008 )
- [x] Proposal on nirvana codegen
- [x] Integration with basic framework
- [x] Testing
- [ ] Detailed documentation on how to generate API docs

@liubog2008

**Comment by ddysher** [comment]
@liubog2008 @Jimexist  Action Items after 4th meeting:
- Proposal on how codegen should work in nirvana 

@Jimexist Please loop in to this feature.

**Comment by liubog2008** [comment]
## action items:
### basic
- [ ] integrate `kube-openapi` with  our `Defininition` struct
- [ ] support our own tag (fork or rewrite)
- [ ] examples

### advanced
- [ ] support common error response
- [ ] support validator
- [ ] support example
- [ ] support common parameters

### another topic
- [ ] support external/internal group conversion by config (used by hodor)
- [ ] support security spec

### in the future
- [ ] support openapi 3.0

**Comment by liubog2008** [comment]
@ddysher @Jimexist

**Comment by ddysher** [comment]
@liubog2008 every single item in ur list sounds like a bit of work, what's the attack plan?

For example, should we start from this first?  Is it doable now? If so, how long will it take? when will you or @Jimexist be able to send out initial implementation for review?
> integrate kube-openapi with our Defininition struct

**Comment by ddysher** [comment]
Action Items after 4th meeting:
- Initial PR on integration of `kube-openapi` and `nirvana`

**Comment by ddysher** [comment]
@liubog2008  I've filed issue to include validator support.  I need more information to decide whether certain features are required for our initial release.

**Comment by liubog2008** [comment]
- support common error response: support doc of error returned by framework, e.g. 404
- support example, generate a real example of API in doc
- support common parameters: e.g. start, limit 

By the way, a detailed doc for business error (defined in handler function) is a problem which is not in plan.

**Comment by kdada** [comment]
Finished in #209. If there are some other questions, please file new issues.
