### ISSUE TITLE
[Umbrella] prometheus instrumentation and profiling

### ISSUE THREAD

**Issue by ddysher** [caicloud/nirvana#6]
Umbrella issue for tracking prometheus instrumentation tasks, scopes:
- [x] Research on required metrics
- [x] Research on profiling
- [x] Proposal on metrics and profiling
- [x] Integration with basic framework
- [x] Documentation, e.g. meaning of metrics, etc
- [x] Testing

@caitong93

**Comment by ddysher** [comment]
@caitong93  Action Items after 4th meeting:
- LGTM on basic framework implementation before 11/24/2017
- LGTM on configuration management before 11/24/2017
- Draft proposal on instrumentation works in nirvana

**Comment by caitong93** [comment]
## Package change:

/nirvana
  /kit
    |---- metrics.go
    |---- profiling.go
    |---- config.go

## Implementation

We will install pprof and prometheus metrics routes into web.Server

```
// config.go

type Config struct {
	EnableProfiling bool
	// Requires generic profiling enabled
	EnableContentionProfiling bool
	EnableMetrics             bool
}

func InstallAPI(s web.Server, c *Config) {
	if c.EnableProfiling {
		Profiling{}.Install(s)
		if c.EnableContentionProfiling {
			runtime.SetBlockProfileRate(1)
		}
	}
	if c.EnableMetrics {
		Metrics{}.Install(s)
	}
}
```

```
// metrics.go

// Metrics installs the default prometheus metrics handler
type Metrics struct{}

var metricsDescriptor = definition.Descriptor{
	Path: "/metrics",
	Definitions: []definition.Definition{
		{
			Method:   definition.Get,
			Function: metricsHandler,
		},
	},
}

var prometheusMetricsHandler = prometheus.Handler()

func metricsHandler(ctx context.Context) {
	r := web.HTTPRequest(ctx)
	w := web.HTTPResponseWriter(ctx)
	prometheusMetricsHandler.ServeHTTP(w, r)
}

func (d Metrics) Install(s web.Server) {
	s.AddDescriptors(metricsDescriptor)
}
```

**Comment by ddysher** [comment]
@caitong93 Discussed offline, a top layer needs to be added to decouple `kit` and `web`.

Action Items after 5th meeting:
- Integration of metrics, profiling with `nirvana`

**Comment by ddysher** [comment]
Done 🚀
