### ISSUE TITLE
Agenda for 12/13/2017 Meeting

### ISSUE THREAD

**Issue by Jimexist** [caicloud/nirvana#61]
# Topics

## Previous action items
- Configuration
  - [x] @zoumo  https://github.com/caicloud/nirvana/pull/45
- Validation
  - [x] @walktall https://github.com/caicloud/nirvana/pull/46
- Instrumentation
  - [ ] @caitong93 https://github.com/caicloud/nirvana/pull/48
- Project [folder] re-arrangement
  - [ ] @kdada 
- Tracing 
  - [ ] @yejiayu https://github.com/caicloud/nirvana/pull/56
- OpenAPI Update
  - [ ] @liubog2008 https://github.com/caicloud/nirvana/pull/57
- Start adding more documentation?
  - [ ] @walktall 
  - [ ] @zoumo https://github.com/caicloud/nirvana/pull/54
- Example project
  - [ ] @Jimexist https://github.com/caicloud/nirvana/pull/49

## To-dos
- Walk-through issues
- Repository setup?
  - labels, milestones, etc
- Others
  - errors? @walktall 
  - log? @zoumo 
  - framework done? if yes, next items? @kdada 
    - router change 405, xxx
    - tracing matching routes?  Fill issue
    - re-org

## Action Items
- Do we need a logo?
- Next Meeting Time ??

**Comment by ddysher** [comment]
Initial labels

- kind
  - kind/feature
  - kind/bug
  - kind/cleanup
  - kind/design
  - kind/enhancement
  - kind/feature
- priority
  - priority/p0
  - priority/p1
  - priority/p2
  - priority/p3
- area
  - area/codegen
  - area/instrumentation
  - area/api
  - area/framework
  - area/configuration
  - area/validation
  - area/test

**Comment by ddysher** [comment]
We are a little bit behind our schedule, let's have next meeting on 12/15/2017.
