### ISSUE TITLE
[Umbrella] Tracing

### ISSUE THREAD

**Issue by ddysher** [caicloud/nirvana#7]
Umbrella issue for tracking tracing tasks, scopes:
- [x] Research on tracing tools and client
- [ ] Proposal on tracing, how it works in the framework
- [x] Integration with basic framework
- [ ] Documentation
- [ ] Testing

@ddysher @xiaoq17

**Comment by ddysher** [comment]
@yejiayu Action Items after 4th meeting:
- Draft proposal on how tracing works in nirvana

**Comment by yejiayu** [comment]
# Draft
## Tracing middleware
### Before
- start span
- Set `Protocol + HTTP Method + Path` to operation name (route support?)
- Set tags
- Set request to span logs. If it's a `GET, DELETE` records `query`, `POST PUT`  records `body`
### After
- Set status code, error..etc to  tags
- Set reponse to logs
## Wrap HTTP Client?
## Wrap clientset?

**Comment by ddysher** [comment]
@yejiayu need to give a demo (15min) on 12/01/2017.
