### ISSUE TITLE
Agenda for 12/15/2017 Meeting

### ISSUE THREAD

**Issue by ddysher** [caicloud/nirvana#76]
# Topics

## PR Updates

- Error package
  - [ ] @walktall https://github.com/caicloud/nirvana/pull/53
- Validation
  - [ ] @walktall https://github.com/caicloud/nirvana/pull/70
- Tracing
  - [ ] @yejiayu https://github.com/caicloud/nirvana/pull/56
- Configuration
  - [ ] @zoumo https://github.com/caicloud/nirvana/pull/55
- OpenAPI Gen
  - [ ] @liubog2008 https://github.com/caicloud/nirvana/pull/57
- Examples
  - [ ] @kdada  https://github.com/caicloud/nirvana/pull/71
  - [ ] @Jimexist https://github.com/caicloud/nirvana/pull/49

## TODOs

- Issue assignment
- Deadline check
  - From [proposal](https://github.com/caicloud/nirvana/issues/1)
  - Agree on v0.1.0 release timeline + items to fix
    - Create P1 issues @caicloud/review-framework 
- More examples (and assignment)
- Proposal on project refinement @kdada []
  - Project organization
  - Package clean up
  - Definition for codegen

## Action Items

- Next Meeting Time
