### ISSUE TITLE
Agenda for 12/20/2017 Meeting

### ISSUE THREAD

**Issue by Jimexist** [caicloud/nirvana#91]
# 回顾过去

[prev meeting](https://github.com/caicloud/nirvana/issues/76)

## PR Updates

- [x] Error package @walktall https://github.com/caicloud/nirvana/pull/53
- [x] Validation @walktall https://github.com/caicloud/nirvana/pull/70
- [x] Tracing @yejiayu https://github.com/caicloud/nirvana/pull/56
- [x] Configuration @zoumo https://github.com/caicloud/nirvana/pull/55
- [ ] OpenAPI Gen @liubog2008 https://github.com/caicloud/nirvana/pull/57
- [x] Examples @kdada  https://github.com/caicloud/nirvana/pull/71
- [x] Examples @Jimexist https://github.com/caicloud/nirvana/pull/49

## Milestone

https://github.com/caicloud/nirvana/milestone/1

# 把握现在

- Logo https://github.com/caicloud/nirvana/issues/69
- More plan on Swapi example project @Jimexist https://github.com/caicloud/nirvana/issues/85
- Code structure @kdada https://github.com/caicloud/nirvana/issues/83

## PRs going over

- [x] move `/website` https://github.com/caicloud/nirvana/pull/90
- [x] add `golint` https://github.com/caicloud/nirvana/pull/88

## Issue assignment

- https://github.com/caicloud/nirvana/issues/73 `@kdada` `12/22/2017`
- https://github.com/caicloud/nirvana/issues/75 `@kdada` `12/22/2017`
- https://github.com/caicloud/nirvana/issues/72 `@liubog2008` `01/01/2018`
- https://github.com/caicloud/nirvana/issues/67 `@kdada` `12/22/2017`
- https://github.com/caicloud/nirvana/issues/63 `@kdada` `12/22/2017`

# 展望未来

- Next Meeting Time:
  - 12/29/2017

**Comment by ddysher** [comment]
fruitful meeting.  close.
